const
  gsTaurusTLSVersionMajor = 2;
  {$NODEFINE gsTaurusTLSVersionMajor}
  gsTaurusTLSVersionMinor = 0;
  {$NODEFINE gsTaurusTLSVersionMinor}
  gsTaurusTLSVersionRelease = 0;
  {$NODEFINE gsTaurusTLSVersionRelease}
  gsTaurusTLSVersionBuild = 47;
  {$NODEFINE gsTaurusTLSVersionBuild}

  (*$HPPEMIT '#define gsTaurusTLSVersionMajor 2'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionMinor 0'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionRelease 0'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionBuild 47'*)
  (*$HPPEMIT ''*)

  gsTaurusTLSVersion = '2.0.0.47'; {do not localize}
  gsTaurusTLSProductName = 'TaurusTLS';  {do not localize}
  gsTaurusTLSProductVersion = '2.0.0.47'; {do not localize}
